Foundations - Global styles
Brayan1425/rulea-bootcamp-questionary pull request #2
Opened 2023-02-17 17:19 UTC by Brayan1425

add global styles and paginations.

2023-02-21 14:05 UTC, Theweeksad approved these changes
very good, you changed the readme

2023-02-21 14:19 UTC, francoo-trainer commented on main.css
> +
avoid making line break

2023-02-21 14:20 UTC, francoo-trainer commented on main.css
> +
avoid making line break

2023-02-21 14:21 UTC, francoo-trainer commented
nice! 
avoid making line break

2023-02-22 14:14 UTC, Jasoneto requested changes
Changes approved.

2023-02-22 14:16 UTC, johanmendezb approved these changes

2023-02-22 14:27 UTC, Jasoneto approved these changes
the ticket is already done.

2023-02-22 14:27 UTC, Brayan1425 commented on main.css
> +
fixed, thank you very much

2023-02-22 14:27 UTC, Brayan1425 commented on main.css
> +
fixed, thank you very much

2023-02-22 15:36 UTC, francoo-trainer approved these changes

2023-02-23 19:14 UTC, merged