CSS homepage
Brayan1425/rulea-bootcamp-questionary pull request #3
Opened 2023-02-23 20:08 UTC by Brayan1425

i added link of the css homepage

2023-02-24 15:18 UTC, Theweeksad requested changes
you have two CSS home page folders, please delete one folder, only the folder that has no code in it

2023-02-28 14:12 UTC, Theweeksad approved these changes
I see that everything is fine

2023-03-01 13:03 UTC, johanmendezb requested changes
Please check the comments, and avoid repeating code specially for margins, add those in the main container

2023-03-01 13:03 UTC, johanmendezb commented on css/homepage.css
> +    margin: 80px 0px 40px 0px;
Please avoid margin top unless is the page/main container margin

2023-03-01 13:03 UTC, johanmendezb commented on css/homepage.css
> +    margin: 30px;
please use only margin bottom

2023-03-01 13:03 UTC, johanmendezb commented on css/homepage.css
> +    margin: 35px 35px 40px 30px;
Please Avoid margin top unless is the page/main container margins

2023-03-01 13:03 UTC, johanmendezb commented on css/homepage.css
> +    height: 260px;
Avoid giving fixed values for section's height.

2023-03-01 16:11 UTC, ripsamuel commented
Please attach screenshots of the layout

2023-03-09 03:00 UTC, ripsamuel commented on css/global-styles.css
> +}
pls use relative measurements

2023-03-09 03:01 UTC, ripsamuel approved these changes

2023-03-09 03:01 UTC, ripsamuel commented on css/global-styles.css
> +}
and attach  ss!!  :(

2023-03-13 22:14 UTC, merged